### ISSUE TITLE
[Refactor] getUser, getBoard, getBoardGroup에 대한 논의

### ISSUE THREAD

**Issue by tjdwns5063** [RollingPaper42/Back-End#123]
# Description
- 저 메서드들이 필요할까요?
- 지금 getBoardGroup 메서드가 BoardService에도 존재하고 BoardGorupService에도 존재.
- getUser처럼 BoardGroupService에만 getBoardGroup 메서드를 남기면, BoardService에서 이 메서드를 사용하려면 BoardGroupService를 주입받아야 한다.
- 그럼 BoardService에서 BoardGroup의 모든 public 메서드에 대해 접근 가능하기 때문에 좋지 않은 패턴이라 생각됨. 필요한 부분에 비해 불필요한 부분이 너무 많이 노출된다고 생각.
- 이에 대해 논의를 해보면 좋겠습니다.

# 고민
- [ ] repository에 구현
- [ ] 서비스마다 구현
- [ ] 레이어 하나 더 만들어서 상속

**Comment by brixxt27** [comment]
#151 이나 이후 리팩토링 요소로 다뤄질 예정
