### ISSUE TITLE
[Feat] 보드와 보드그룹의 암호화 로직 서로 겹치지 않게 변경

### ISSUE THREAD

**Issue by eesum** [RollingPaper42/Back-End#73]
# Description
- board, board-group 조회 시 "아이디 + 생성 시간" 조합으로 암호화 키를 만들어 db에 저장

# To do
- [ ]

**Comment by tjdwns5063** [comment]
보드 및 보드그룹 암호화 로직을 어떻게 변경하는 부분일까요??

**Comment by brixxt27** [comment]
직전에 진행한 암호화 알고리즘 변경 PR에 포함되는 이슈라 닫겠습니다.
